### ISSUE TITLE
rewrite everything using proper best practices

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport-slack#122]
We should consider doing a major rewrite of everything from bottom up. I'm talking about implementing everything from scratch with a proper design and plan from the beginning using all the "open issues" we have.

Example would be ... 

- Slack blocks
- using requests instead of slack package and talking to the web api
- proper architecture and design before we start implementing any code to minimize any future refactoring
etc ..

this could be done as a major version bump. We could get away with doing it for the tr-slack only and consider doing the same thing after for the tr-api if we feel that it is necessary.

Right now it feels like we have too many open tickets that depend on each other before we can move forward and most of the refactoring will be huge changes anyway ... so maybe we should outline an proper plan / design etc and move forward with a total rewrite.

thoughts?

**Comment by parberge** [comment]
Can we identify what design etc that is not good enough? I personally really like making something that exists better but I also feel that we have a problem moving forward with the current code base. I believe this happens when we focus to much on features rather than spending a good amount of time on refactoring

**Comment by kamigerami** [comment]
sure - we can close this down and discuss specifics in one of our sessions.
