### ISSUE TITLE
Verify slack token

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#87]
We have a function `verify_token`, but it's never used.
So we don't actually verify that the request is from slack it seems. We should do that 😄

**Comment by kamigerami** [comment]
Agreed! Tho the methods have changed in how we verify secrets! The new procedures are the following:  https://api.slack.com/docs/verifying-requests-from-slack

```
How to make a request signature in 4 easy steps: an overview
Ingredients required: one (1) HTTP request from Slack, one (1) signing secret, one (1) programming language of your choice.

Here's an overview of the process to validate a signed request from Slack:

Retrieve the X-Slack-Request-Timestamp header on the HTTP request, and the body of the request.
Concatenate the version number, the timestamp, and the body of the request to form a basestring. Use a colon as the delimiter between the three elements. For example, v0:123456789:command=/weather&text=94070. The version number right now is always v0.
With the help of HMAC SHA256 implemented in your favorite programming, hash the above basestring, using the Slack Signing Secret as the key.
Compare this computed signature to the X-Slack-Signature header on the request.
```

**Comment by kamigerami** [comment]
Reopening this issue as we need to add a new TOKEN to it.

We are currently using the "Bot User OAuth Access Token" as config['slack_token'] however this is just for communication between the bot and the users so that we can "post" messages to channels and people.

We also need to verify that we are talking to timereport via slack by using the "signing_secret" which is a different token altogether. 

This requires us to add another token to the configuration and use that when we run "verify_token".
